### ISSUE TITLE
PageSpeed InSlides Error

### ISSUE THREAD

**Issue by emrecan-s** [google/pagespeed-inslides#7]
Hi,
 I am facing with  API error when I try to analyze a URL. I am using only page speed insights API key.
The API works well with an another page speed insight project that I am working on.
Thanks for the help,
![screenshot_1](https://user-images.githubusercontent.com/36107830/50573225-1ea50280-0dd0-11e9-9dfc-d958e376df8f.png)![dot](https://user-images.githubusercontent.com/36107830/50573248-d0dcca00-0dd0-11e9-8746-e008e0757eab.jpg)

)

**Comment by emrecan-s** [comment]
Changing the API variable in pagespeed.js solved my issue issue. const API_KEY = 'your key'.
Also I have the  pug compile issue after this.

**Comment by tomayac** [comment]
You are supposed to change the file name of `dot.env` to `.env`, then the API key is found and you don’t have to edit the source code.

**Comment by emrecan-s** [comment]
> You are supposed to change the file name of `dot.env` to `.env`, then the API key is found and you don’t have to edit the source code.

Hi Thomas,
Thanks for the answer, yes it worked with Linux.
